# Justfile for {{cookiecutter.package_name}}
PLACEHOLDER := '{{cookiecutter.package_name}}'


# Show available commands
list:
    echo "🧠 just commands for  {{cookiecutter.package_name}}"
    @just --list

